  final List<String> cityItems = [
    "Karachi",
    "New York City",
    "London",
    "Toronto",
    "Sydney",
    "Berlin",
    "Paris",
    "Tokyo",
    "Rio de Janeiro",
    "Beijing",
    "Mumbai",
    "Johannesburg",
    "Mexico City",
    "Rome",
    "Barcelona",
    "Moscow",
    "Seoul",
    "Buenos Aires",
  ];

  final List<String> nationalityItems = [
    "Pakistan",
    "United States",
    "United Kingdom",
    "Canada",
    "Australia",
    "Germany",
    "France",
    "Japan",
    "Brazil",
    "China",
    "India",
    "South Africa",
    "Mexico",
    "Italy",
    "Spain",
    "Russia",
    "South Korea",
    "Argentina",
  ];
  final List<String> roomTypesItems = [
    '1 Room, 2 Adults, 0 Children',
    '2 Room, 4 Adults, 2 Children',
    '5 Room, 10 Adults, 8 Children',
  ];